<Project Sdk="Aspire.AppHost.Sdk/13.0.2">

  <ItemGroup>
    <ProjectReference Include="..\BlazorApp1\BlazorApp1.csproj" />
    <ProjectReference Include="..\WebShopApi\WebShopApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>2d9aaf42-de0e-4ac0-85c9-b9e2802f3932</UserSecretsId>
  </PropertyGroup>

</Project>
